#!/usr/bin/env bash

DRAFT_HOME=~/coding/blog/blog-draft/
FROM_DOC_DIR=$DRAFT_HOME/published
FROM_ASSETS_DIR=$DRAFT_HOME/assets

migrate_doc() {
    convmdblog $FROM_DOC_DIR ./_posts d j
}

sync_assets() {
    rsync -avP --exclude-from='./rsync_exclude.txt' $FROM_ASSETS_DIR/ ./assets
}

sync_assets
migrate_doc
